version: "3.8"

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user_django:pass_django@db:5432/db_django
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_django
      - POSTGRES_PASSWORD=pass_django
      - POSTGRES_DB=db_django

volumes:
  postgres_data:
